<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adf010a0b68656c6c6f2e70726f746f120568656c6c6f221c0a0c48656c" .
            "6c6f52657175657374120c0a046e616d6518012001280922200a0d48656c" .
            "6c6f526573706f6e7365120f0a076d657373616765180120012809328001" .
            "0a0548656c6c6f12370a0853617948656c6c6f12132e68656c6c6f2e4865" .
            "6c6c6f526571756573741a142e68656c6c6f2e48656c6c6f526573706f6e" .
            "73652200123e0a0d4c6f74734f665265706c69657312132e68656c6c6f2e" .
            "48656c6c6f526571756573741a142e68656c6c6f2e48656c6c6f52657370" .
            "6f6e736522003001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

